package tabelaAcoes;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author Lucas
 */
public class FrmTabelaAcoes extends javax.swing.JFrame {

    private CtrFrmTabelaAcoes listenerCtrAcoes;

    /**
     * Creates new form FrmTabela
     */
    public FrmTabelaAcoes() {
        initComponents();
        listenerCtrAcoes = new CtrFrmTabelaAcoes(this);
    }

    public JButton getBtnAddAcao() {
        return btnAddAcao;
    }

    public void setBtnAddAcao(JButton btnAddAcao) {
        this.btnAddAcao = btnAddAcao;
    }

    public JButton getBtnNewAcao() {
        return btnNewAcao;
    }

    public void setBtnNewAcao(JButton btnNewAcao) {
        this.btnNewAcao = btnNewAcao;
    }

    public JButton getBtnPassarTurno() {
        return btnPassarTurno;
    }

    public void setBtnPassarTurno(JButton btnPassarTurno) {
        this.btnPassarTurno = btnPassarTurno;
    }

    public JTable getTbAcoes() {
        return tbAcoes;
    }

    public void setTbAcoes(JTable tbAcoes) {
        this.tbAcoes = tbAcoes;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddAcao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAcoes = new javax.swing.JTable();
        btnNewAcao = new javax.swing.JButton();
        btnPassarTurno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAddAcao.setText("Adicionar Ação");

        tbAcoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Ações", "Ações", "Ações", "Ações"
            }
        ));
        tbAcoes.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tbAcoes);
        tbAcoes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbAcoes.getColumnModel().getColumnCount() > 0) {
            tbAcoes.getColumnModel().getColumn(0).setResizable(false);
            tbAcoes.getColumnModel().getColumn(0).setCellEditor(null);
            tbAcoes.getColumnModel().getColumn(0).setCellRenderer(null);
        }

        btnNewAcao.setText("Nova ação selecionada");

        btnPassarTurno.setText("Teste passar turno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddAcao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPassarTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewAcao)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAcao)
                    .addComponent(btnNewAcao)
                    .addComponent(btnPassarTurno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTabelaAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTabelaAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTabelaAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTabelaAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTabelaAcoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAcao;
    private javax.swing.JButton btnNewAcao;
    private javax.swing.JButton btnPassarTurno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbAcoes;
    // End of variables declaration//GEN-END:variables
}
