package jogo.visao;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import jogo.controle.CtrFrmAcao;
import jogo.modelo.Acao;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Tela de detalhes e operações das alções
 *
 * @author Lucas
 */
public class FrmAcao extends javax.swing.JFrame {

    CtrFrmAcao listeners;
    Acao acao;

    /**
     * Creates new form AcaoInfoFRM
     */
    public FrmAcao() {
        initComponents();
        listeners = new CtrFrmAcao(this);
    }

    FrmAcao(Acao acao) {
        initComponents();
        this.setAcao(acao);
        listeners = new CtrFrmAcao(this);
    }

    public Acao getAcao() {
        return acao;
    }

    public void setAcao(Acao acao) {
        this.acao = acao;
        this.getLblNomeValor().setText(String.valueOf(acao.getNome()));
        this.getLblPrecoUniValor().setText(String.valueOf("R$" + acao.getValor()));
        this.getLblQuantidadeValor().setText(String.valueOf(acao.getQuantidade()));
        this.getLblVariacaoValor().setText(String.valueOf(acao.getVariacao() + "%"));

    }

    public JButton getBtnVender() {
        return BtnVender;
    }

    public void setBtnVender(JButton BtnVender) {
        this.BtnVender = BtnVender;
    }

    public JButton getBtnComprar() {
        return btnComprar;
    }

    public void setBtnComprar(JButton btnComprar) {
        this.btnComprar = btnComprar;
    }

    public JButton getBtnMaisInfo() {
        return btnMaisInfo;
    }

    public void setBtnMaisInfo(JButton btnMaisInfo) {
        this.btnMaisInfo = btnMaisInfo;
    }

    public JLabel getLblNomeEmpresaValor() {
        return lblNomeEmpresaValor;
    }

    public void setLblNomeEmpresaValor(JLabel lblNomeEmpresaValor) {
        this.lblNomeEmpresaValor = lblNomeEmpresaValor;
    }

    public JLabel getLblNomeValor() {
        return lblNomeValor;
    }

    public void setLblNomeValor(JLabel lblNomeValor) {
        this.lblNomeValor = lblNomeValor;
    }

    public JLabel getLblPrecoUniValor() {
        return lblPrecoUniValor;
    }

    public void setLblPrecoUniValor(JLabel lblPrecoUniValor) {
        this.lblPrecoUniValor = lblPrecoUniValor;
    }

    public JLabel getLblQuantidadeValor() {
        return lblQuantidadeValor;
    }

    public void setLblQuantidadeValor(JLabel lblQuantidadeValor) {
        this.lblQuantidadeValor = lblQuantidadeValor;
    }

    public JLabel getLblStatusEmpresaValor() {
        return lblStatusEmpresaValor;
    }

    public void setLblStatusEmpresaValor(JLabel lblStatusEmpresaValor) {
        this.lblStatusEmpresaValor = lblStatusEmpresaValor;
    }

    public JLabel getLblVariacaoValor() {
        return lblVariacaoValor;
    }

    public void setLblVariacaoValor(JLabel lblVariacaoValor) {
        this.lblVariacaoValor = lblVariacaoValor;
    }

    public JPanel getPanelActionAcao() {
        return panelActionAcao;
    }

    public void setPanelActionAcao(JPanel panelActionAcao) {
        this.panelActionAcao = panelActionAcao;
    }

    public JPanel getPanelInfoAcao() {
        return panelInfoAcao;
    }

    public void setPanelInfoAcao(JPanel panelInfoAcao) {
        this.panelInfoAcao = panelInfoAcao;
    }

    public JScrollPane getScrollTbAcoesCompra() {
        return scrollTbAcoesCompra;
    }

    public void setScrollTbAcoesCompra(JScrollPane scrollTbAcoesCompra) {
        this.scrollTbAcoesCompra = scrollTbAcoesCompra;
    }

    public JScrollPane getScrollTbAcoesVenda() {
        return scrollTbAcoesVenda;
    }

    public void setScrollTbAcoesVenda(JScrollPane scrollTbAcoesVenda) {
        this.scrollTbAcoesVenda = scrollTbAcoesVenda;
    }

    public JTable getTbAcoesCompra() {
        return tbAcoesCompra;
    }

    public void setTbAcoesCompra(JTable tbAcoesCompra) {
        this.tbAcoesCompra = tbAcoesCompra;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelActionAcao = new javax.swing.JPanel();
        panelInfoAcao = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblPrecoUni = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        lblQuantidadeValor = new javax.swing.JLabel();
        lblVariacao = new javax.swing.JLabel();
        lblVariacaoValor = new javax.swing.JLabel();
        lblNomeValor = new javax.swing.JLabel();
        lblPrecoUniValor = new javax.swing.JLabel();
        lblNomeEmpresa = new javax.swing.JLabel();
        lblNomeEmpresaValor = new javax.swing.JLabel();
        lblStatusEmpresa = new javax.swing.JLabel();
        lblStatusEmpresaValor = new javax.swing.JLabel();
        btnMaisInfo = new javax.swing.JButton();
        scrollTbAcoesCompra = new javax.swing.JScrollPane();
        tbAcoesCompra = new javax.swing.JTable();
        scrollTbAcoesVenda = new javax.swing.JScrollPane();
        tbAcoesVenda = new javax.swing.JTable();
        btnComprar = new javax.swing.JButton();
        BtnVender = new javax.swing.JButton();
        lblOrdensCompra = new javax.swing.JLabel();
        lblOrdensVenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelActionAcao.setLayout(new java.awt.GridBagLayout());

        lblNome.setText("Nome:");

        lblPrecoUni.setText("Preço Unitário:");

        lblQuantidade.setText("Quantidade:");

        lblQuantidadeValor.setText("N");

        lblVariacao.setText("Variação:");

        lblVariacaoValor.setText("N%");

        lblNomeValor.setText("Nome");

        lblPrecoUniValor.setText("R$0,00");

        lblNomeEmpresa.setText("Empresa:");

        lblNomeEmpresaValor.setText("NomeEmpresa");

        lblStatusEmpresa.setText("Status:");

        lblStatusEmpresaValor.setText("StatusEmpresa");

        btnMaisInfo.setText("Mais informações");

        javax.swing.GroupLayout panelInfoAcaoLayout = new javax.swing.GroupLayout(panelInfoAcao);
        panelInfoAcao.setLayout(panelInfoAcaoLayout);
        panelInfoAcaoLayout.setHorizontalGroup(
            panelInfoAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoAcaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoAcaoLayout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomeValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVariacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVariacaoValor))
                    .addGroup(panelInfoAcaoLayout.createSequentialGroup()
                        .addGroup(panelInfoAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInfoAcaoLayout.createSequentialGroup()
                                .addComponent(lblPrecoUni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPrecoUniValor))
                            .addGroup(panelInfoAcaoLayout.createSequentialGroup()
                                .addComponent(lblQuantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblQuantidadeValor))
                            .addGroup(panelInfoAcaoLayout.createSequentialGroup()
                                .addComponent(lblNomeEmpresa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNomeEmpresaValor))
                            .addGroup(panelInfoAcaoLayout.createSequentialGroup()
                                .addComponent(lblStatusEmpresa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStatusEmpresaValor)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelInfoAcaoLayout.createSequentialGroup()
                .addComponent(btnMaisInfo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelInfoAcaoLayout.setVerticalGroup(
            panelInfoAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoAcaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblVariacao)
                    .addComponent(lblVariacaoValor)
                    .addComponent(lblNomeValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecoUniValor)
                    .addComponent(lblPrecoUni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidade)
                    .addComponent(lblQuantidadeValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeEmpresa)
                    .addComponent(lblNomeEmpresaValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusEmpresa)
                    .addComponent(lblStatusEmpresaValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMaisInfo)
                .addGap(50, 50, 50))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = -48;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelActionAcao.add(panelInfoAcao, gridBagConstraints);

        tbAcoesCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        scrollTbAcoesCompra.setViewportView(tbAcoesCompra);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelActionAcao.add(scrollTbAcoesCompra, gridBagConstraints);

        tbAcoesVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        scrollTbAcoesVenda.setViewportView(tbAcoesVenda);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelActionAcao.add(scrollTbAcoesVenda, gridBagConstraints);

        btnComprar.setText("Comprar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelActionAcao.add(btnComprar, gridBagConstraints);

        BtnVender.setText("Vender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelActionAcao.add(BtnVender, gridBagConstraints);

        lblOrdensCompra.setText("Ordens de Compra");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelActionAcao.add(lblOrdensCompra, gridBagConstraints);

        lblOrdensVenda.setText("Ordens de Venda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelActionAcao.add(lblOrdensVenda, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelActionAcao, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelActionAcao, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAcao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVender;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnMaisInfo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeEmpresa;
    private javax.swing.JLabel lblNomeEmpresaValor;
    private javax.swing.JLabel lblNomeValor;
    private javax.swing.JLabel lblOrdensCompra;
    private javax.swing.JLabel lblOrdensVenda;
    private javax.swing.JLabel lblPrecoUni;
    private javax.swing.JLabel lblPrecoUniValor;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblQuantidadeValor;
    private javax.swing.JLabel lblStatusEmpresa;
    private javax.swing.JLabel lblStatusEmpresaValor;
    private javax.swing.JLabel lblVariacao;
    private javax.swing.JLabel lblVariacaoValor;
    private javax.swing.JPanel panelActionAcao;
    private javax.swing.JPanel panelInfoAcao;
    private javax.swing.JScrollPane scrollTbAcoesCompra;
    private javax.swing.JScrollPane scrollTbAcoesVenda;
    private javax.swing.JTable tbAcoesCompra;
    private javax.swing.JTable tbAcoesVenda;
    // End of variables declaration//GEN-END:variables

}
