package jogo.visao;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import jogo.controle.CtrActionDetails;
import jogo.modelo.Action;

/**
 * Tela de detalhes e operações das alções
 *
 * @see Action
 * @see CtrActionDetails
 */
public class FrmActionDetails extends javax.swing.JFrame {

    private final CtrActionDetails listeners;
    private Action action;

    /**
     * Creates new form AcaoInfoFRM
     */
    public FrmActionDetails() {
        initComponents();
        listeners = new CtrActionDetails(this);
    }

    public FrmActionDetails(Action acao) {
        initComponents();
        this.action = acao;
        listeners = new CtrActionDetails(this);
    }

    public CtrActionDetails getListeners() {
        return listeners;
    }

    public Action getAction() {
        return action;
    }

    public void setAction(Action action) {
        this.action = action;
    }

    public JButton getBtnComprar() {
        return btnComprar;
    }

    public void setBtnComprar(JButton btnComprar) {
        this.btnComprar = btnComprar;
    }

    public JButton getBtnOrdens() {
        return btnOrdens;
    }

    public void setBtnOrdens(JButton btnOrdens) {
        this.btnOrdens = btnOrdens;
    }

    public JButton getBtnVender() {
        return btnVender;
    }

    public void setBtnVender(JButton btnVender) {
        this.btnVender = btnVender;
    }

    public JLabel getLblNomeValor() {
        return lblNomeValor;
    }

    public void setLblNomeValor(JLabel lblNomeValor) {
        this.lblNomeValor = lblNomeValor;
    }

    public JLabel getLblPrecoUniValor() {
        return lblPrecoUniValor;
    }

    public void setLblPrecoUniValor(JLabel lblPrecoUniValor) {
        this.lblPrecoUniValor = lblPrecoUniValor;
    }

    public JLabel getLblQuantidadeJogadorValor() {
        return lblQuantidadeJogadorValor;
    }

    public void setLblQuantidadeJogadorValor(JLabel lblQuantidadeJogadorValor) {
        this.lblQuantidadeJogadorValor = lblQuantidadeJogadorValor;
    }

    public JLabel getLblStatusAcaoValor() {
        return lblStatusAcaoValor;
    }

    public void setLblStatusAcaoValor(JLabel lblStatusAcaoValor) {
        this.lblStatusAcaoValor = lblStatusAcaoValor;
    }

    public JLabel getLblVariacaoValor() {
        return lblVariacaoValor;
    }

    public void setLblVariacaoValor(JLabel lblVariacaoValor) {
        this.lblVariacaoValor = lblVariacaoValor;
    }

    public JTable getTbAcoesCompra() {
        return tbAcoesCompra;
    }

    public void setTbAcoesCompra(JTable tbAcoesCompra) {
        this.tbAcoesCompra = tbAcoesCompra;
    }

    public JTable getTbAcoesVenda() {
        return tbAcoesVenda;
    }

    public void setTbAcoesVenda(JTable tbAcoesVenda) {
        this.tbAcoesVenda = tbAcoesVenda;
    }

    public JLabel getLblQuantidadeValor() {
        return lblQuantidadeValor;
    }

    public void setLblQuantidadeValor(JLabel lblQuantidadeValor) {
        this.lblQuantidadeValor = lblQuantidadeValor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelActionAcao = new javax.swing.JPanel();
        panelInfoAcao = new javax.swing.JPanel();
        lblVariacaoValor = new javax.swing.JLabel();
        lblStatusAction = new javax.swing.JLabel();
        lblVariacao = new javax.swing.JLabel();
        lblPrecoUniValor = new javax.swing.JLabel();
        lblPrecoUni = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        lblQuantidadeValor = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblStatusAcaoValor = new javax.swing.JLabel();
        lblNomeValor = new javax.swing.JLabel();
        scrollTbAcoesCompra = new javax.swing.JScrollPane();
        tbAcoesCompra = new javax.swing.JTable();
        scrollTbAcoesVenda = new javax.swing.JScrollPane();
        tbAcoesVenda = new javax.swing.JTable();
        btnComprar = new javax.swing.JButton();
        btnVender = new javax.swing.JButton();
        lblOrdensCompra = new javax.swing.JLabel();
        lblOrdensVenda = new javax.swing.JLabel();
        panelInfoJogador = new javax.swing.JPanel();
        lblQuantidadeJogador = new javax.swing.JLabel();
        lblDadosJogado = new javax.swing.JLabel();
        lblQuantidadeJogadorValor = new javax.swing.JLabel();
        btnOrdens = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelActionAcao.setLayout(new java.awt.GridBagLayout());

        lblVariacaoValor.setText("N%");

        lblStatusAction.setText("Status:");

        lblVariacao.setText("Variação:");

        lblPrecoUniValor.setText("R$0,00");

        lblPrecoUni.setText("Preço Unitário:");

        lblQuantidade.setText("Quantidade no Mercado:");

        lblQuantidadeValor.setText("N");

        lblNome.setText("Nome:");

        lblStatusAcaoValor.setText("StatusAcao");

        lblNomeValor.setText("Nome");

        javax.swing.GroupLayout panelInfoAcaoLayout = new javax.swing.GroupLayout(panelInfoAcao);
        panelInfoAcao.setLayout(panelInfoAcaoLayout);
        panelInfoAcaoLayout.setHorizontalGroup(
            panelInfoAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoAcaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoAcaoLayout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomeValor))
                    .addGroup(panelInfoAcaoLayout.createSequentialGroup()
                        .addComponent(lblPrecoUni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrecoUniValor))
                    .addGroup(panelInfoAcaoLayout.createSequentialGroup()
                        .addComponent(lblQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantidadeValor))
                    .addGroup(panelInfoAcaoLayout.createSequentialGroup()
                        .addComponent(lblStatusAction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatusAcaoValor))
                    .addGroup(panelInfoAcaoLayout.createSequentialGroup()
                        .addComponent(lblVariacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVariacaoValor)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        panelInfoAcaoLayout.setVerticalGroup(
            panelInfoAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoAcaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblNomeValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecoUni)
                    .addComponent(lblPrecoUniValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidade)
                    .addComponent(lblQuantidadeValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusAction)
                    .addComponent(lblStatusAcaoValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelInfoAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVariacao)
                    .addComponent(lblVariacaoValor))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelActionAcao.add(panelInfoAcao, gridBagConstraints);

        tbAcoesCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Quantidade", "Valor"
            }
        ));
        scrollTbAcoesCompra.setViewportView(tbAcoesCompra);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelActionAcao.add(scrollTbAcoesCompra, gridBagConstraints);

        tbAcoesVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Quantidade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTbAcoesVenda.setViewportView(tbAcoesVenda);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelActionAcao.add(scrollTbAcoesVenda, gridBagConstraints);

        btnComprar.setText("Comprar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelActionAcao.add(btnComprar, gridBagConstraints);

        btnVender.setText("Vender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelActionAcao.add(btnVender, gridBagConstraints);

        lblOrdensCompra.setText("Ordens de Compra");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelActionAcao.add(lblOrdensCompra, gridBagConstraints);

        lblOrdensVenda.setText("Ordens de Venda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelActionAcao.add(lblOrdensVenda, gridBagConstraints);

        panelInfoJogador.setMinimumSize(new java.awt.Dimension(100, 100));
        panelInfoJogador.setPreferredSize(new java.awt.Dimension(170, 198));

        lblQuantidadeJogador.setText("Quantidade de ações:");

        lblDadosJogado.setText("Dados do Jogador");

        lblQuantidadeJogadorValor.setText("N");

        btnOrdens.setText("Minhas Ordens");

        javax.swing.GroupLayout panelInfoJogadorLayout = new javax.swing.GroupLayout(panelInfoJogador);
        panelInfoJogador.setLayout(panelInfoJogadorLayout);
        panelInfoJogadorLayout.setHorizontalGroup(
            panelInfoJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoJogadorLayout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(panelInfoJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoJogadorLayout.createSequentialGroup()
                        .addComponent(lblQuantidadeJogador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantidadeJogadorValor))
                    .addComponent(lblDadosJogado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOrdens, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panelInfoJogadorLayout.setVerticalGroup(
            panelInfoJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoJogadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDadosJogado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadeJogadorValor)
                    .addComponent(lblQuantidadeJogador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnOrdens)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelActionAcao.add(panelInfoJogador, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelActionAcao, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelActionAcao, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmActionDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmActionDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmActionDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmActionDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmActionDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnOrdens;
    private javax.swing.JButton btnVender;
    private javax.swing.JLabel lblDadosJogado;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeValor;
    private javax.swing.JLabel lblOrdensCompra;
    private javax.swing.JLabel lblOrdensVenda;
    private javax.swing.JLabel lblPrecoUni;
    private javax.swing.JLabel lblPrecoUniValor;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblQuantidadeJogador;
    private javax.swing.JLabel lblQuantidadeJogadorValor;
    private javax.swing.JLabel lblQuantidadeValor;
    private javax.swing.JLabel lblStatusAcaoValor;
    private javax.swing.JLabel lblStatusAction;
    private javax.swing.JLabel lblVariacao;
    private javax.swing.JLabel lblVariacaoValor;
    private javax.swing.JPanel panelActionAcao;
    private javax.swing.JPanel panelInfoAcao;
    private javax.swing.JPanel panelInfoJogador;
    private javax.swing.JScrollPane scrollTbAcoesCompra;
    private javax.swing.JScrollPane scrollTbAcoesVenda;
    private javax.swing.JTable tbAcoesCompra;
    private javax.swing.JTable tbAcoesVenda;
    // End of variables declaration//GEN-END:variables

}
