package jogo.visao;

import javax.swing.JButton;
import javax.swing.JTable;
import jogo.controle.CtrSaveRecovery;

/**
 * Tela de Carregamento dos jogos salvos no Banco de dados.
 *
 * @see Game
 * @see CtrSaveRecovery
 */
public class FrmSaveRecovery extends javax.swing.JFrame {

    private final CtrSaveRecovery listeners;

    /**
     * Creates new form FrmCarregarJogo
     */
    public FrmSaveRecovery() {
        initComponents();
        listeners = new CtrSaveRecovery(this);
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/jogo/img/WinIcon.png")).getImage());
    }

    public CtrSaveRecovery getListeners() {
        return listeners;
    }

    public JButton getBtnCarregarJogo() {
        return btnCarregarJogo;
    }

    public void setBtnCarregarJogo(JButton btnCarregarJogo) {
        this.btnCarregarJogo = btnCarregarJogo;
    }

    public JButton getBtnVoltar() {
        return btnVoltar;
    }

    public void setBtnVoltar(JButton btnVoltar) {
        this.btnVoltar = btnVoltar;
    }

    public JTable getTbCarregarJogo() {
        return tbCarregarJogo;
    }

    public void setTbCarregarJogo(JTable tbCarregarJogo) {
        this.tbCarregarJogo = tbCarregarJogo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelCarregar = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        scrollTbCarregarJogo = new javax.swing.JScrollPane();
        tbCarregarJogo = new javax.swing.JTable();
        btnCarregarJogo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carregar Jogo");
        setMinimumSize(new java.awt.Dimension(300, 300));

        panelCarregar.setBackground(new java.awt.Color(153, 153, 153));
        panelCarregar.setLayout(new java.awt.GridBagLayout());

        btnVoltar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVoltar.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelCarregar.add(btnVoltar, gridBagConstraints);

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 204));
        lblTitulo.setText("Jogos Salvos");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        panelCarregar.add(lblTitulo, gridBagConstraints);

        scrollTbCarregarJogo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tbCarregarJogo.setBackground(new java.awt.Color(153, 153, 153));
        tbCarregarJogo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tbCarregarJogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Nome do Jogador", "Saldo", "Turno", "Salvo em..."
            }
        ));
        tbCarregarJogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbCarregarJogo.setOpaque(false);
        scrollTbCarregarJogo.setViewportView(tbCarregarJogo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 493;
        gridBagConstraints.ipady = 308;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelCarregar.add(scrollTbCarregarJogo, gridBagConstraints);

        btnCarregarJogo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnCarregarJogo.setText("Carregar Jogo");
        btnCarregarJogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCarregarJogo.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        panelCarregar.add(btnCarregarJogo, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 523, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCarregar, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSaveRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSaveRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSaveRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSaveRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSaveRecovery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregarJogo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelCarregar;
    private javax.swing.JScrollPane scrollTbCarregarJogo;
    private javax.swing.JTable tbCarregarJogo;
    // End of variables declaration//GEN-END:variables
}
