package jogo.visao;

import javax.swing.JButton;
import javax.swing.JPanel;
import jogo.controle.CtrStart;

/**
 * Tela de Início do Jogo.
 *
 * @see CtrStart
 */
public class FrmStart extends javax.swing.JFrame {

    private CtrStart listener;

    /**
     * Creates new form FrmStart
     */
    public FrmStart() {
        initComponents();
        this.listener = new CtrStart(this);
    }

    public CtrStart getListener() {
        return listener;
    }

    public void setListener(CtrStart listener) {
        this.listener = listener;
    }

    public JButton getBtnNovoJogo() {
        return BtnNovoJogo;
    }

    public void setBtnNovoJogo(JButton BtnNovoJogo) {
        this.BtnNovoJogo = BtnNovoJogo;
    }

    public JButton getBtnCarregarJogo() {
        return btnCarregarJogo;
    }

    public void setBtnCarregarJogo(JButton btnCarregarJogo) {
        this.btnCarregarJogo = btnCarregarJogo;
    }

    public JPanel getPanelStart() {
        return panelStart;
    }

    public void setPanelStart(JPanel panelStart) {
        this.panelStart = panelStart;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelStart = new javax.swing.JPanel();
        BtnNovoJogo = new javax.swing.JButton();
        btnCarregarJogo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 300));

        panelStart.setLayout(new java.awt.GridBagLayout());

        BtnNovoJogo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BtnNovoJogo.setText("Novo Jogo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelStart.add(BtnNovoJogo, gridBagConstraints);

        btnCarregarJogo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCarregarJogo.setText("Carregar Jogo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        panelStart.add(btnCarregarJogo, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelStart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelStart, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmStart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNovoJogo;
    private javax.swing.JButton btnCarregarJogo;
    private javax.swing.JPanel panelStart;
    // End of variables declaration//GEN-END:variables
}
