/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo.visao;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Lucas
 */
public class FrmTelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmTelaPrincipal
     */
    public FrmTelaPrincipal() {
        initComponents();
    }

    public JButton getBtnPassarTurno() {
        return btnPassarTurno;
    }

    public void setBtnPassarTurno(JButton btnPassarTurno) {
        this.btnPassarTurno = btnPassarTurno;
    }

    public JButton getBtnPatrimonio() {
        return btnPatrimonio;
    }

    public void setBtnPatrimonio(JButton btnPatrimonio) {
        this.btnPatrimonio = btnPatrimonio;
    }

    public JButton getBtnVisaoGeral() {
        return btnVisaoGeral;
    }

    public void setBtnVisaoGeral(JButton btnVisaoGeral) {
        this.btnVisaoGeral = btnVisaoGeral;
    }

    public JMenuBar getFrmMenuBar() {
        return frmMenuBar;
    }

    public void setFrmMenuBar(JMenuBar frmMenuBar) {
        this.frmMenuBar = frmMenuBar;
    }

    public JLabel getLblNomeValor() {
        return lblNomeValor;
    }

    public void setLblNomeValor(JLabel lblNomeValor) {
        this.lblNomeValor = lblNomeValor;
    }

    public JLabel getLblSaldoValor() {
        return lblSaldoValor;
    }

    public void setLblSaldoValor(JLabel lblSaldoValor) {
        this.lblSaldoValor = lblSaldoValor;
    }

    public JLabel getLblTurnoValor() {
        return lblTurnoValor;
    }

    public void setLblTurnoValor(JLabel lblTurnoValor) {
        this.lblTurnoValor = lblTurnoValor;
    }

    public JMenu getMenuAjuda() {
        return menuAjuda;
    }

    public void setMenuAjuda(JMenu menuAjuda) {
        this.menuAjuda = menuAjuda;
    }

    public JMenuItem getMenuItemSalvar() {
        return menuItemSalvar;
    }

    public void setMenuItemSalvar(JMenuItem menuItemSalvar) {
        this.menuItemSalvar = menuItemSalvar;
    }

    public JMenu getMenuJogo() {
        return menuJogo;
    }

    public void setMenuJogo(JMenu menuJogo) {
        this.menuJogo = menuJogo;
    }

    public JPanel getPanelDados() {
        return panelDados;
    }

    public void setPanelDados(JPanel panelDados) {
        this.panelDados = panelDados;
    }

    public JPanel getPanelTelaPrincipal() {
        return panelTelaPrincipal;
    }

    public void setPanelTelaPrincipal(JPanel panelTelaPrincipal) {
        this.panelTelaPrincipal = panelTelaPrincipal;
    }

    public JScrollPane getScrollPaneTabelaAcoes() {
        return scrollPaneTabelaAcoes;
    }

    public void setScrollPaneTabelaAcoes(JScrollPane scrollPaneTabelaAcoes) {
        this.scrollPaneTabelaAcoes = scrollPaneTabelaAcoes;
    }

    public JTable getTabelaAcoes() {
        return tabelaAcoes;
    }

    public void setTabelaAcoes(JTable tabelaAcoes) {
        this.tabelaAcoes = tabelaAcoes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTelaPrincipal = new javax.swing.JPanel();
        panelDados = new javax.swing.JPanel();
        btnPassarTurno = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblSaldoValor = new javax.swing.JLabel();
        btnVisaoGeral = new javax.swing.JButton();
        btnPatrimonio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblNomeValor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTurnoValor = new javax.swing.JLabel();
        scrollPaneTabelaAcoes = new javax.swing.JScrollPane();
        tabelaAcoes = new javax.swing.JTable();
        frmMenuBar = new javax.swing.JMenuBar();
        menuJogo = new javax.swing.JMenu();
        menuItemSalvar = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPassarTurno.setText("Passar de Turno");

        jLabel1.setText("Saldo:");

        lblSaldoValor.setText("saldoValor");

        btnVisaoGeral.setText("Visão Geral do Mercado");

        btnPatrimonio.setText("Meu Patrimonio");

        jLabel2.setText("Nome:");

        lblNomeValor.setText("nomeValor");

        jLabel3.setText("Turno:");

        lblTurnoValor.setText("turnoValor");

        javax.swing.GroupLayout panelDadosLayout = new javax.swing.GroupLayout(panelDados);
        panelDados.setLayout(panelDadosLayout);
        panelDadosLayout.setHorizontalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTurnoValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPassarTurno))
                    .addGroup(panelDadosLayout.createSequentialGroup()
                        .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDadosLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNomeValor))
                            .addGroup(panelDadosLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSaldoValor)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVisaoGeral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPatrimonio)))
                .addContainerGap())
        );
        panelDadosLayout.setVerticalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPassarTurno)
                    .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblTurnoValor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosLayout.createSequentialGroup()
                        .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblNomeValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblSaldoValor))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPatrimonio)
                        .addComponent(btnVisaoGeral)))
                .addContainerGap())
        );

        tabelaAcoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ações", "Ações", "Ações", "Ações", "Ações", "Ações", "Ações", "Ações", "Ações"
            }
        ));
        tabelaAcoes.setCellSelectionEnabled(true);
        tabelaAcoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        scrollPaneTabelaAcoes.setViewportView(tabelaAcoes);
        if (tabelaAcoes.getColumnModel().getColumnCount() > 0) {
            tabelaAcoes.getColumnModel().getColumn(0).setMinWidth(150);
            tabelaAcoes.getColumnModel().getColumn(1).setMinWidth(150);
            tabelaAcoes.getColumnModel().getColumn(2).setMinWidth(150);
            tabelaAcoes.getColumnModel().getColumn(3).setMinWidth(150);
            tabelaAcoes.getColumnModel().getColumn(4).setMinWidth(150);
            tabelaAcoes.getColumnModel().getColumn(5).setMinWidth(150);
            tabelaAcoes.getColumnModel().getColumn(6).setMinWidth(150);
            tabelaAcoes.getColumnModel().getColumn(7).setMinWidth(150);
            tabelaAcoes.getColumnModel().getColumn(8).setMinWidth(150);
        }

        javax.swing.GroupLayout panelTelaPrincipalLayout = new javax.swing.GroupLayout(panelTelaPrincipal);
        panelTelaPrincipal.setLayout(panelTelaPrincipalLayout);
        panelTelaPrincipalLayout.setHorizontalGroup(
            panelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTelaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneTabelaAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTelaPrincipalLayout.setVerticalGroup(
            panelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTelaPrincipalLayout.createSequentialGroup()
                .addComponent(panelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneTabelaAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuJogo.setText("Jogo");

        menuItemSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemSalvar.setText("Salvar");
        menuJogo.add(menuItemSalvar);

        frmMenuBar.add(menuJogo);

        menuAjuda.setText("Ajuda");
        frmMenuBar.add(menuAjuda);

        setJMenuBar(frmMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPassarTurno;
    private javax.swing.JButton btnPatrimonio;
    private javax.swing.JButton btnVisaoGeral;
    private javax.swing.JMenuBar frmMenuBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNomeValor;
    private javax.swing.JLabel lblSaldoValor;
    private javax.swing.JLabel lblTurnoValor;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuItem menuItemSalvar;
    private javax.swing.JMenu menuJogo;
    private javax.swing.JPanel panelDados;
    private javax.swing.JPanel panelTelaPrincipal;
    private javax.swing.JScrollPane scrollPaneTabelaAcoes;
    private javax.swing.JTable tabelaAcoes;
    // End of variables declaration//GEN-END:variables
}
