package jogo.visao;

import java.awt.Component;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import jogo.modelo.Action;

/**
 * Representação de uma ação gráfica
 *
 * @see Action
 */
public class PanelAction extends javax.swing.JPanel {

    private Action acao;

    public PanelAction() {
        initComponents();

        //Style Editor
        for (Component myComponent : getMyComponents()) {
            if (myComponent instanceof JLabel) {
                ((JLabel) myComponent).setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                ((JLabel) myComponent).setVerticalAlignment(javax.swing.SwingConstants.CENTER);
            }
        }

        //Button Action
        this.getBtnInformacao().addActionListener((ActionEvent e) -> {
            FrmActionDetails frmAcao = new FrmActionDetails(acao);
            frmAcao.setVisible(true);
        });
    }

    public void reloadMyComponents() {
        this.lblNome.setText(acao.getName());
        this.lblPreco.setText("R$" + String.valueOf(acao.getValue()));
        this.lblVariacao.setText(String.valueOf(acao.getVariation()) + '%');
    }

    public Component[] getMyComponents() {
        Component[] myComponents = {
            this.getBtnInformacao(),
            this.getLblNome(),
            this.getLblPreco(),
            this.getLblVariacao()
        };
        return myComponents;
    }

    public Action getAcao() {
        return acao;
    }

    public void setAcao(Action acao) {
        this.acao = acao;
        this.reloadMyComponents();
    }

    public JButton getBtnInformacao() {
        return btnInformacao;
    }

    public void setBtnInformacao(JButton jlblInformacao) {
        this.btnInformacao = jlblInformacao;
    }

    public JLabel getLblNome() {
        return lblNome;
    }

    public void setLblNome(JLabel jlblNome) {
        this.lblNome = jlblNome;
    }

    public JLabel getLblPreco() {
        return lblPreco;
    }

    public void setLblPreco(JLabel jlblPreco) {
        this.lblPreco = jlblPreco;
    }

    public JLabel getLblVariacao() {
        return lblVariacao;
    }

    public void setLblVariacao(JLabel jlblVariacao) {
        this.lblVariacao = jlblVariacao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDados = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblVariacao = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        btnInformacao = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(150, 75));
        setMinimumSize(new java.awt.Dimension(150, 75));
        setPreferredSize(new java.awt.Dimension(150, 75));

        panelDados.setLayout(new java.awt.GridLayout(2, 2));

        lblNome.setBackground(new java.awt.Color(204, 204, 204));
        lblNome.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblNome.setText("     Nome:");
        lblNome.setAlignmentX(5.0F);
        lblNome.setFocusable(false);
        lblNome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelDados.add(lblNome);

        lblVariacao.setBackground(new java.awt.Color(153, 153, 153));
        lblVariacao.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblVariacao.setText("Variação %");
        lblVariacao.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        lblVariacao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelDados.add(lblVariacao);

        lblPreco.setBackground(new java.awt.Color(153, 153, 153));
        lblPreco.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPreco.setText("     Preço:");
        lblPreco.setToolTipText("");
        lblPreco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelDados.add(lblPreco);

        btnInformacao.setBackground(new java.awt.Color(204, 204, 204));
        btnInformacao.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnInformacao.setText("Info");
        btnInformacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInformacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelDados.add(btnInformacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDados, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInformacao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblVariacao;
    private javax.swing.JPanel panelDados;
    // End of variables declaration//GEN-END:variables
}
